spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
#    url: jdbc:mariadb://localhost:3306/article1db
    username: ${db.username}
#    username: root
    password: ${db.password}
#    password: mariadb

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.api.client_id}
            client-secret: ${google.api.client_secret}
            scope:
              - email
              - profile
          # 네이버는 기본적으로 provider가 아니다. 그래서 추가적인 설정 파일이 있다. 아래 코드 참고.
          naver:
            client-id: ${naver.api.client_id}
            client-secret: ${naver.api.client_secret}
            scope:
              - name
              - gender
              - birthday
              - birthyear
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${naver.api.redirect_uri}

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.sql: debug

springdoc:
  swagger-ui:
    path: /
    groups-order: DESC # path, query, body, response 순으로 출력




