spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

  profiles:
    include: aws

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import:
      - optional:file:.env[.properties]

logging:
  level:
    org.hibernate.sql: debug




